### ISSUE TITLE
Datei als URL anbieten

### ISSUE THREAD

**Issue by thethinker990** [stelas/Feiertage#1]
Ist es möglich die Datei als URL anzubieten? Ich möchte es gerne in meine Web-Oberfläche einbinden und kann dort keine Dateien hochladen sondern nur Links angeben.

**Comment by stelas** [comment]
Gute Idee, habe ich mit 8b32989a07eb53a27ae75e651394c8a34baedea3 und 88febcc15b8aa699eaf9412bd8295840742286c8 umgesetzt.

Dateinamen der Form "Feiertage\<Länderkürzel\>\<Jahr\>.ics" ermöglichen einen direkten Download; für deutschlandweiten Kalender das Kürzel weglassen.
Bsp.: [https://feiertage-kalender.de/FeiertageBB2024.ics](https://feiertage-kalender.de/FeiertageBB2024.ics) oder [https://feiertage-kalender.de/Feiertage2024.ics](https://feiertage-kalender.de/Feiertage2024.ics)
